### ISSUE TITLE
Improve FL Studio automation support

### ISSUE THREAD

**Issue by jonorozcoc** [greatest-ape/OctaSine#118]
I just installed the plugin and I tried to automate the controls without any luck. Is there a way to support it?

If that's the case, I can help testing.

**Comment by greatest-ape** [comment]
It should be supported.. Are you using version 0.8.1? In that case, could you please test with the previous release? https://github.com/greatest-ape/OctaSine/releases/tag/v0.8.0

**Comment by jonorozcoc** [comment]
I'll check it @greatest-ape

**Comment by jonorozcoc** [comment]
My bad @greatest-ape, the latest version has automation support, actually. I found the available events.

**Comment by jonorozcoc** [comment]
Btw, I found some events are treated as knobs instead of triggers

**Comment by jonorozcoc** [comment]
I'll send a video to show you what I mean

**Comment by jonorozcoc** [comment]
https://user-images.githubusercontent.com/8442497/200141311-0e15b922-a80e-42a0-977b-506784f005d1.mp4

As you can see in the video I'm toggling the mute button for the LFO4 but it shows as a knob

**Comment by jonorozcoc** [comment]
https://user-images.githubusercontent.com/8442497/200141340-64b6bd13-cacf-462e-81c7-5dd1d655a955.mp4

I do the same with another plugin and it shows as a toggle

**Comment by greatest-ape** [comment]
Thanks for checking and great that it works with 0.8.1.

Is the other thing causing issues when automating or is it just confusing / not pretty? :-) And is the other plugin a vst2 plugin?

**Comment by jonorozcoc** [comment]
I think is not intuitive as a switch. The main reason is to avoid intermediate values when automating that can produce misleading effects. Aside that, I don't have any issue with it.

**Comment by jonorozcoc** [comment]
And yes, it's a VST 2 plugin

**Comment by greatest-ape** [comment]
Alright, sure, that makes sense.

**Comment by bryc** [comment]
That's how VST parameters work in FL Studio or in general. They're basically a decimal between 0 and 1 and developers typically define thresholds to implement toggle buttons.  It's always been this way, in fact, the very first VST made (Neon) has a 'octave' selector with a hidden option only available my manually adjusting the raw parameter in the way you're doing it. 

So it's a non-issue.

The reason Harmor does the 'snap' thing is because it's an FLi plugin, not a VSTi plugin, and supports 'lists' of options directly on the raw knob control, because it's a native FL thing. This is simply not possible to do with the raw parameters.

**Comment by greatest-ape** [comment]
Hmm yeah, we’re not going to get snapping widgets in DAWs, and I don’t think it’s a good idea to try to automate parameters when they’re set. So I’m closing this issue.
