### ISSUE TITLE
Exposed symbols on local build

### ISSUE THREAD

**Issue by tank-trax** [greatest-ape/OctaSine#150]
Successfully built clap and vst3 on Debian 11

after building noticed that both plugins exposed an extra symbol

for example the prebuilt binaries I downloaded 

```
objdump -T OctaSine\ v0.8.clap | grep ' g '
0000000000368408 g    DO .data.rel.ro   0000000000000028  Base        clap_entry
```
```
objdump -T OctaSine\ v0.8.so | grep ' g '
00000000000bd6c0 g    DF .text  0000000000000005  Base        VSTPluginMain
```

```
objdump -T octasine.clap | grep ' g '
00000000000af400 g    DF .text  0000000000000005  Base        VSTPluginMain
000000000038aca8 g    DO .data.rel.ro   0000000000000028  Base        clap_entry
```

```
objdump -T octasine.so | grep ' g '
00000000000af400 g    DF .text  0000000000000005  Base        VSTPluginMain
000000000038aca8 g    DO .data.rel.ro   0000000000000028  Base        clap_entry
```

still no GUI in Bitwig

however.... as the bleeding edge does not have the orange box to open GUI

![image](https://user-images.githubusercontent.com/41337033/223484010-ab26df8a-bb2d-42dd-9347-899c6c076878.png)

the master branch does, however it does not open, it tries then disappears

![image](https://user-images.githubusercontent.com/41337033/223483893-75c67639-28f9-4eda-b8d8-0480fe36fc8d.png)

**Comment by greatest-ape** [comment]
Thanks.

Is the GUI working in Bitwig with any of vst or clap formats on master branch?

**Comment by tank-trax** [comment]
the VST GUI loads in Bitwig, the VST and CLAP GUI loads in Reaper

**Comment by greatest-ape** [comment]
Thanks! When you open the VST GUI in Bitwig, are there any other issues? I've got it to load on macOS but resources are not freed properly when the plugin window is closed, so every time that the window is opened again, CPU consumption increases. Hopefully, this issue is not present on Linux.

Regarding the symbols, the fix is to pass `--no-default-features --features "glow vst2"` or `--no-default-features --features "glow clap"` to the cargo xtask build command, which is indeed done for the prebuilt binaries. I'll update the README.

**Comment by greatest-ape** [comment]
I’ve updated the README.
