### ISSUE TITLE
Feature request: shorter envelopes

### ISSUE THREAD

**Issue by kzantow** [greatest-ape/OctaSine#85]
**Describe the bug**
The smallest amount one can adjust the envelopes is not small enough for the needs of some percussive sounds. For example, zooming in all the way like like this:
![image](https://user-images.githubusercontent.com/3009477/187030277-eb2069ff-638e-41ac-95b3-e64bb2d6b5ff.png)
With noise yields an audible volume ramp-up, which is not ideal for things like hi-hats, see the corresponding waveform, approximately 20 milliseconds:
![image](https://user-images.githubusercontent.com/3009477/187030652-1b47b1a2-005a-48cc-9b4e-8654b9ad4fd4.png)

**What did you try to do**
- Enable a single operator
- Set to noise
- Adjust envelope to the smallest attack and decay possible, sustain 0

**Expected behavior**
There is no volume ramp up -- ideally, the attack phase could be length of 0, and either no decay (no sound) or a very fast < 5ms sound.

**Screenshots**
(added in description)

**Software (please complete the following information):**
 - OctaSine version: v0.7.0 (the info button is lower-right btw)
 - DAW: Bitwig 4.3.4
 - OS: Windows 10

**Comment by greatest-ape** [comment]
@kzantow Thanks.

The minimum envelope stage length is currently 10ms, as you indicated. Making it shorter means increasing the risk of appearance of audio artefacts such as clicks, especially when there is an interaction with LFOs.

There might however be a lower value which still enables your use case. I'll try to look into it.

**Comment by kzantow** [comment]
Thanks for looking at this! I agree about the possibility of audio artefacts, however when using _noise_ or other high frequency content this generally wouldn't an issue, which is one the main use case for this request.

**Comment by greatest-ape** [comment]
Sure, that's true. I want to keep using the same envelope logic for both noise and sine modes, though.

I tried changing the min length to 3ms. I also implemented a fix for your other issue, so that oneshot LFOs stay at the end value. I've done some testing and it seems to work fine so far.

Would you mind trying out the changes? There are some other unreleased changes since 0.7 too, so your patches will likely have to be adjusted, notably modulation output amount, panning and LFO target selection.

[OctaSine-tmp-2022-08-26_3-Windows.zip](https://github.com/greatest-ape/OctaSine/files/9438462/OctaSine-tmp-2022-08-26_3-Windows.zip)

[OctaSine-tmp-2022-08-26_3-macOS-Intel.zip](https://github.com/greatest-ape/OctaSine/files/9438463/OctaSine-tmp-2022-08-26_3-macOS-Intel.zip)

[OctaSine-tmp-2022-08-26_3-Ubuntu-20_04.zip](https://github.com/greatest-ape/OctaSine/files/9438464/OctaSine-tmp-2022-08-26_3-Ubuntu-20_04.zip)

**Comment by kzantow** [comment]
I gave this a try -- definitely an improvement for both issues! Able to get a kick drum with a transient like this now:
![image](https://user-images.githubusercontent.com/3009477/187043707-7872acb9-abee-497f-8529-be227d06313d.png)
This opens up a lot better sound design for percussive sounds 👍

**Comment by greatest-ape** [comment]
Great!

If you have time, it would be great if you could try it out a bit more and see if you encounter any bugs.

**Comment by greatest-ape** [comment]
I’ve merged the changes, so I’m closing the issue :-)
